import Point from "./Point";
import { GraphicImplType } from "./types";
import GeomObject from "./base/GeomObject";
import Transformation from "./transformation";
import Geomtoy from ".";
import { AreaMeasurable } from "./interfaces";
declare class Ellipse extends GeomObject implements AreaMeasurable {
    #private;
    constructor(owner: Geomtoy, centerX: number, centerY: number, radiusX: number, radiusY: number, rotation?: number);
    constructor(owner: Geomtoy, centerCoordinate: [number, number], radiusX: number, radiusY: number, rotation?: number);
    constructor(owner: Geomtoy, centerPoint: Point, radiusX: number, radiusY: number, rotation?: number);
    get name(): string;
    get uuid(): string;
    get centerX(): number;
    set centerX(value: number);
    get centerY(): number;
    set centerY(value: number);
    get centerCoordinate(): [number, number];
    set centerCoordinate(value: [number, number]);
    get centerPoint(): Point;
    set centerPoint(value: Point);
    get radiusX(): number;
    set radiusX(value: number);
    get radiusY(): number;
    set radiusY(value: number);
    get rotation(): number;
    set rotation(value: number);
    getEccentricity(): void;
    clone(): GeomObject;
    toString(): string;
    toObject(): object;
    toArray(): any[];
    getGraphic(type: GraphicImplType): (import("./types").SvgDirective | import("./types").CanvasDirective)[];
    static findTangentLineOfTwoEllipse(ellipse1: Ellipse, ellipse2: Ellipse): void;
    static findTangentLineOfEllipseAndParabola(): void;
    apply(transformation: Transformation): GeomObject;
    getPerimeter(): number;
    getArea(): number;
    getGraphicAlt(type: GraphicImplType): (import("./types").SvgDirective | import("./types").CanvasDirective)[];
}
export default Ellipse;
