import Point from "../Point";
import Line from "../Line";
import Matrix from "../transformation/Matrix";
import { Coordinate } from "../types";
declare function geomObjectD0Mixin<T extends abstract new (...args: any[]) => any>(c: T): (abstract new (...args: any[]) => {
    [x: string]: any;
    translate(offsetX: number, offsetY: number): any;
    translateSelf(offsetX: number, offsetY: number): any;
    rotate(angle: number, origin: Point): any;
    rotateSelf(angle: number, origin: Point): any;
    scale(factorX: number, factorY: number, origin: Point): any;
    scaleSelf(factorX: number, factorY: number, origin: Point): any;
    skew(angleX: number, angleY: number, origin: Point): any;
    skewSelf(angleX: number, angleY: number, origin: Point): any;
    lineReflect(line: Line): any;
    lineReflectSelf(line: Line): any;
    pointReflect(point: Point): any;
    pointReflectSelf(point: Point): any;
    transform(matrix: Matrix): any;
    transformSelf(matrix: Matrix): any;
    normalize(): any;
    normalizeSelf(): any;
    getCoordinate(): Coordinate;
}) & T;
export default geomObjectD0Mixin;
